redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9092"
  topic: "article_localCacheUpdate_event"
  consumer_group: "articleRanking"

grpc:
  server:
    addr: ":8092"
  client:
    intr:
      addr: ":8090"
    article:
      addr: ":8091"

node:
  id: "ranking-node-1"  # 可以通过环境变量或启动参数覆盖
