// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XD/ScholarNet/cmd/payment/grpc"
	"github.com/XD/ScholarNet/cmd/payment/ioc"
	"github.com/XD/ScholarNet/cmd/payment/repository"
	"github.com/XD/ScholarNet/cmd/payment/repository/dao"
	"github.com/XD/ScholarNet/cmd/payment/web"
	"github.com/XD/ScholarNet/cmd/pkg/wego"
)

// Injectors from wire.go:

func InitApp() *wego.App {
	wechatConfig := ioc.InitWechatConfig()
	handler := ioc.InitWechatNotifyHandler(wechatConfig)
	client := ioc.InitWechatClient(wechatConfig)
	db := ioc.InitDB()
	paymentDAO := dao.NewPaymentGORMDAO(db)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	loggerV1 := ioc.InitLogger()
	saramaClient := ioc.InitKafka()
	producer := ioc.InitProducer(saramaClient)
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, loggerV1, producer, wechatConfig)
	wechatHandler := web.NewWechatHandler(handler, nativePaymentService, loggerV1)
	server := ioc.InitGinServer(wechatHandler)
	wechatServiceServer := grpc.NewWechatServiceServer(nativePaymentService)
	clientv3Client := ioc.InitEtcdClient()
	grpcxServer := ioc.InitGRPCServer(wechatServiceServer, clientv3Client, loggerV1)
	app := &wego.App{
		WebServer:  server,
		GRPCServer: grpcxServer,
	}
	return app
}
