// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XD/ScholarNet/cmd/follow/grpc"
	"github.com/XD/ScholarNet/cmd/follow/ioc"
	"github.com/XD/ScholarNet/cmd/follow/repository"
	"github.com/XD/ScholarNet/cmd/follow/repository/cache"
	"github.com/XD/ScholarNet/cmd/follow/repository/dao"
	"github.com/XD/ScholarNet/cmd/follow/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	followRelationDao := dao.NewFollowRelationDao(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRepository(followRelationDao, followCache, loggerV1)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowServiceServer(followRelationService)
	server := ioc.InitGRPCxServer(followServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger)

var serviceProvider = wire.NewSet(dao.NewFollowRelationDao, cache.NewRedisFollowCache, repository.NewFollowRepository, service.NewFollowRelationService, grpc.NewFollowServiceServer)
