// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XD/ScholarNet/cmd/interactive/events"
	"github.com/XD/ScholarNet/cmd/interactive/grpc"
	"github.com/XD/ScholarNet/cmd/interactive/ioc"
	"github.com/XD/ScholarNet/cmd/interactive/repository"
	"github.com/XD/ScholarNet/cmd/interactive/repository/cache"
	"github.com/XD/ScholarNet/cmd/interactive/repository/dao"
	"github.com/XD/ScholarNet/cmd/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	srcDB := ioc.InitSRC()
	dstDB := ioc.InitDST()
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	loggerV1 := ioc.InitLogger()
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveCache, interactiveDAO, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCxServer(interactiveServiceServer)
	client := ioc.InitKafka()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(client, interactiveRepository, loggerV1)
	consumer := ioc.InitFixDataConsumer(loggerV1, srcDB, dstDB, client)
	v := ioc.NewConsumers(interactiveReadEventConsumer, consumer)
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitMigratorProducer(syncProducer)
	ginxServer := ioc.InitMigratorWeb(srcDB, dstDB, loggerV1, doubleWritePool, producer)
	app := &App{
		server:    server,
		consumers: v,
		webAdmin:  ginxServer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitSRC, ioc.InitDST, ioc.InitBizDB, ioc.InitDoubleWritePool, ioc.InitRedis, ioc.InitKafka, ioc.InitSyncProducer, ioc.InitLogger)

var interactiveSvcProvider = wire.NewSet(service.NewInteractiveService, repository.NewCachedInteractiveRepository, cache.NewRedisInteractiveCache, dao.NewGORMInteractiveDAO)

var migratorProvider = wire.NewSet(ioc.InitMigratorProducer, ioc.InitFixDataConsumer, ioc.InitMigratorWeb)
