// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XD/ScholarNet/cmd/account/grpc"
	"github.com/XD/ScholarNet/cmd/account/ioc"
	"github.com/XD/ScholarNet/cmd/account/repository"
	"github.com/XD/ScholarNet/cmd/account/repository/dao"
	"github.com/XD/ScholarNet/cmd/account/service"
	"github.com/XD/ScholarNet/cmd/pkg/wego"
)

// Injectors from wire.go:

func Init() *wego.App {
	db := ioc.InitDB()
	accountDAO := dao.NewCreditGORMDAO(db)
	accountRepository := repository.NewAccountRepository(accountDAO)
	accountService := service.NewAccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	client := ioc.InitEtcdClient()
	loggerV1 := ioc.InitLogger()
	server := ioc.InitGRPCxServer(accountServiceServer, client, loggerV1)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}
