// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XD/ScholarNet/cmd/pkg/wego"
	"github.com/XD/ScholarNet/cmd/tag/grpc"
	"github.com/XD/ScholarNet/cmd/tag/ioc"
	"github.com/XD/ScholarNet/cmd/tag/repository/cache"
	"github.com/XD/ScholarNet/cmd/tag/repository/dao"
	"github.com/XD/ScholarNet/cmd/tag/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *wego.App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	tagDAO := dao.NewGORMTagDAO(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	tagRepository := ioc.InitRepository(tagDAO, tagCache, loggerV1)
	tagService := service.NewTagService(tagRepository)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(tagServiceServer, client, loggerV1)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitLogger, ioc.InitDB, ioc.InitEtcdClient)
